# Generated by Django 5.0.4 on 2024-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('employee_id', models.IntegerField()),
                ('specialist_id', models.IntegerField()),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
