# Generated by Django 5.0.4 on 2024-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0002_ticket_is_closed_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
