# Generated by Django 5.0.4 on 2024-04-29 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0003_alter_ticket_date_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['is_closed', '-date_opened']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='specialist_id',
            new_name='specialist',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
