# Generated by Django 5.0.4 on 2024-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0004_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='employee',
            field=models.IntegerField(),
        ),
    ]
