# Generated by Django 5.0.4 on 2024-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0006_alter_ticket_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(null=True, upload_to='media/tickets'),
        ),
    ]
