# Generated by Django 5.0.4 on 2024-05-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0007_ticket_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='file',
        ),
    ]
