# Generated by Django 5.0.6 on 2024-05-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0008_remove_ticket_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='specialist',
        ),
    ]
