# Generated by Django 5.0.6 on 2024-06-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0013_remove_report_employee_report_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ticket',
        ),
    ]
