# Generated by Django 5.0.6 on 2024-06-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdver2', '0014_remove_report_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
